### ISSUE TITLE
Not running out of the box: "libEsm is not a function"

### ISSUE THREAD

**Issue by DenysVuika** [electron-vite/electron-vite-react#149]
Running "npm install" and "npm run dev" gives the following error:

```
[commonjs--resolver] libEsm is not a function
error during build:
TypeError: libEsm is not a function
at getSnippets (/node_modules/vite-plugin-electron-renderer/dist/index.js:273:33)
```

Node: v18.14.2
Npm: 9.5.0

**Comment by ramonvc** [comment]
The problem seems to be related to the latest version of the "vite-plugin-electron-renderer" dependency.
To fix it for now, just change the version of this dependency.

In package.json:
"vite-plugin-electron-renderer": "^0.14.3" change to "vite-plugin-electron-renderer": "0.14.2"

Now just delete the node_modules folder and the package-lock.json file and reinstall the dependencies with "yarn" or "npm install"
